name: First_Manually_Created

on:
  # Changed the branch name, so the workflow will not be triggered all the time,
  # cause this is just an education project
  push:
    branches: [ "test" ]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print out all env variables sorted
      run: env | sort
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print out all env variables sorted
      run: "Get-ChildItem Env: | Sort-Object Name"