name: Marketplace Action

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.7.0



 
          
