name: Challenge from chapter 3

on: [push]

env:
  ARTIFACT_NAME: artifact_ch3

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
